server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  sleuth:
    sampler:
      percentage: 1.0                                 # 采样请求的百分比,默认0.1,既10%

      
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


    
