server:
  port: 8081
spring:
   application:
      name: microservice-provider-user
   sleuth:
    sampler:
      percentage: 1.0                                 # 采样请求的百分比,默认0.1,既10%
   jpa:
     generate-ddl: false
     show-sql: true
     hibernate:
       ddl-auto: none
   datasource:                                        # 指定数据源
     driver-class-name: com.mysql.jdbc.Driver         # mysql数据库
     url: jdbc:mysql://localhost/test?useSSL=false    # url
     username: root                                   # 数据库用户名
     password: root                                   # 数据库密码
     schema: classpath:schema.sql                     # 指定数据库的建表脚本
     data: classpath:data.sql                         # 指定数据库的数据脚本
 
     
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest

    
logging:                                              # 配置日志级别,让hibernate打印执行的sql
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    
    

  