server:
  port: 8761
eureka:
  client:
    register-with-eureka: false  #不把自己注册到eureka server 
    fetch-registry: false        #不需要从eureka server获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/  #eureka server交互地址