server:
  port: 8010
spring:
  application:
    name: eureka-client-consumer
user.userServiceUrl: http://localhost:8080/user/

management:
  security:
    enabled: false                                    # 关闭权限认证
    
