server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aabbcc5050/SpringCloudLearn
          search-paths: config-repo
    bus:
      trace:
        enabled: true                               # 开启cloud bus的跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

      
management:
  security:
    enabled: false 