server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aabbcc5050/SpringCloudLearn
          search-paths: config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # http://eureka.didispace.com/eureka/ 
      
management:
  security:
    enabled: false 