server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
    
# zuul.routes.server-name: /url/**    # 配置serviceId = 指定路径
# zuul.ignored-services: server1,server2   # 忽略服务用逗号隔开,不代理这些服务,用 ignored-services: '*'可忽略所有服务
# 使用zuul.ignored-services: '*'忽略所有服务,然后加上zuul.routes.microservice-server: /user/** 可以让zuul只路由microservice-server服务
logging:
  level:
    com.netflix: DEBUG #查看zuul路由的细节
  