server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  zipkin:
    base-url: http://localhost:9411                   # zipkin服务器地址
  sleuth:
    sampler:
      percentage: 1.0                                 # 采样请求的百分比,默认0.1,既10%

    
